### ISSUE TITLE
Passwordless Sign-in (Sign-in Link)

### ISSUE THREAD

**Issue by wikiverse** [sudokim/skku-web-chat#10]
For more information, refer to Issue #9.

**Comment by sudokim** [comment]
I've enabled passwordless sign-in from the Firebase Console.
[This](https://firebase.google.com/docs/auth/web/email-link-auth?authuser=0) is the official documentation for passwordless sign-in.

**Comment by wikiverse** [comment]
Yup, thanks. Working on it.

**Comment by sudokim** [comment]
Will passwordless sign-in be the only method for signing in?
Or are we providing passwordless sign-in as an alternative method for email/password sign-in?

**Comment by wikiverse** [comment]
It's alternative. I am currently combining this feature with My Profile page so that a user stays authenticated through Passwordless Sign-in.
