### ISSUE TITLE
Add Title to `signin.html`

### ISSUE THREAD

**Issue by sudokim** [sudokim/skku-web-chat#2]
The new sign-in page looks awesome, but it lacks a title that displays our app name.
It would be better to have a title on the sign-in page above 'Sign In' and 'About This Project'.

**Comment by wikiverse** [comment]
Should've linked a pull request, but here is the commit:
https://github.com/sudokim/skku-web-chat/commit/127695b77b0866ced1914b1d239c5dda90514157
